options:
  target-user:
    name: цель
    description: Лицо, у которого проверить инвентарь вместо этого

items:
  treasures: {}
  pancakes: {}
_metadata:
  name: инвентарь
  description: Команды, относящиеся к инвентарю игрока
item_entry_template: '**`{spacer}{amount, pretty_num}`** {icon} {name}'
